version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.7.4
    working_directory: ~/repo
    steps:
      # setup
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get

      # checks
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix credo
      - run: mix docs
      - run: mix test
